module.exports = {
	parserOptions: {
		ecmaVersion: 2022,
		sourceType: 'module',
	},

	plugins: ['prettier', 'import', 'n', 'html', 'no-only-tests'],

	extends: [
		'eslint:recommended',
		'plugin:import/recommended',
		'plugin:n/recommended',
		'prettier',
	],

	rules: {
		'accessor-pairs': 'warn',
		'array-callback-return': 'warn',
		'arrow-body-style': 'warn',
		'block-scoped-var': 'warn',
		camelcase: 'warn',
		'capitalized-comments': 'warn',
		'class-methods-use-this': 'warn',
		complexity: 'warn',
		'consistent-return': 'warn',
		'consistent-this': 'warn',
		'default-case': 'warn',
		'default-case-last': 'warn',
		'default-param-last': 'warn',
		'dot-notation': 'warn',
		eqeqeq: 'warn',
		'func-name-matching': 'warn',
		'func-names': 'warn',
		'func-style': 'warn',
		'grouped-accessor-pairs': 'warn',
		'guard-for-in': 'warn',
		'id-denylist': 'warn',
		'id-length': 'warn',
		'id-match': 'warn',
		'import/dynamic-import-chunkname': 'warn',
		'import/exports-last': 'warn',
		'import/extensions': 'warn',
		'import/first': 'warn',
		'import/group-exports': 'warn',
		'import/max-dependencies': 'warn',
		'import/newline-after-import': 'warn',
		'import/no-absolute-path': 'warn',
		'import/no-amd': 'warn',
		'import/no-anonymous-default-export': 'warn',
		'import/no-commonjs': 'warn',
		'import/no-cycle': 'warn',
		'import/no-default-export': 'warn',
		'import/no-deprecated': 'warn',
		'import/no-dynamic-require': 'warn',
		'import/no-extraneous-dependencies': 'warn',
		'import/no-import-module-exports': 'warn',
		'import/no-internal-modules': 'warn',
		'import/no-mutable-exports': 'warn',
		'import/no-named-default': 'warn',
		'import/no-named-export': 'warn',
		'import/no-namespace': 'warn',
		'import/no-nodejs-modules': 'warn',
		'import/no-relative-packages': 'warn',
		'import/no-relative-parent-imports': 'warn',
		'import/no-restricted-paths': 'warn',
		'import/no-self-import': 'warn',
		'import/no-unassigned-import': 'warn',
		'import/no-unused-modules': 'warn',
		'import/no-useless-path-segments': 'warn',
		'import/no-webpack-loader-syntax': 'warn',
		'import/order': 'warn',
		'import/prefer-default-export': 'warn',
		'import/unambiguous': 'warn',
		'init-declarations': 'warn',
		'line-comment-position': 'warn',
		'lines-between-class-members': 'warn',
		'logical-assignment-operators': 'warn',
		'max-classes-per-file': 'warn',
		'max-depth': 'warn',
		'max-lines': 'warn',
		'max-lines-per-function': 'warn',
		'max-nested-callbacks': 'warn',
		'max-params': 'warn',
		'max-statements': 'warn',
		'max-statements-per-line': 'warn',
		'multiline-comment-style': 'warn',
		'n/no-unsupported-features/es-syntax': 'off',
		'n/no-missing-import': 'off',
		'n/callback-return': 'warn',
		'n/exports-style': 'warn',
		'n/file-extension-in-import': 'warn',
		'n/global-require': 'warn',
		'n/handle-callback-err': 'warn',
		'n/no-callback-literal': 'warn',
		'n/no-mixed-requires': 'warn',
		'n/no-new-require': 'warn',
		'n/no-path-concat': 'warn',
		'n/no-process-env': 'warn',
		'n/no-restricted-import': 'warn',
		'n/no-restricted-require': 'warn',
		'n/no-sync': 'warn',
		'n/prefer-global/buffer': 'warn',
		'n/prefer-global/console': 'warn',
		'n/prefer-global/process': 'warn',
		'n/prefer-global/text-decoder': 'warn',
		'n/prefer-global/text-encoder': 'warn',
		'n/prefer-global/url': 'warn',
		'n/prefer-global/url-search-params': 'warn',
		'n/prefer-promises/dns': 'warn',
		'n/prefer-promises/fs': 'warn',
		'new-cap': 'warn',
		'no-alert': 'warn',
		'no-array-constructor': 'warn',
		'no-await-in-loop': 'warn',
		'no-bitwise': 'warn',
		'no-caller': 'warn',
		'no-console': 'warn',
		'no-constant-binary-expression': 'warn',
		'no-constructor-return': 'warn',
		'no-continue': 'warn',
		'no-div-regex': 'warn',
		'no-duplicate-imports': 'warn',
		'no-else-return': 'warn',
		'no-empty-function': 'warn',
		'no-empty-static-block': 'warn',
		'no-eq-null': 'warn',
		'no-eval': 'warn',
		'no-extend-native': 'warn',
		'no-extra-bind': 'warn',
		'no-extra-label': 'warn',
		'no-implicit-coercion': 'warn',
		'no-implicit-globals': 'warn',
		'no-implied-eval': 'warn',
		'no-inline-comments': 'warn',
		'no-invalid-this': 'warn',
		'no-iterator': 'warn',
		'no-label-var': 'warn',
		'no-labels': 'warn',
		'no-lone-blocks': 'warn',
		'no-lonely-if': 'warn',
		'no-loop-func': 'warn',
		'no-magic-numbers': 'warn',
		'no-multi-assign': 'warn',
		'no-multi-str': 'warn',
		'no-negated-condition': 'warn',
		'no-nested-ternary': 'warn',
		'no-new': 'warn',
		'no-new-func': 'warn',
		'no-new-native-nonconstructor': 'warn',
		'no-new-object': 'warn',
		'no-new-wrappers': 'warn',
		'no-octal-escape': 'warn',
		'no-only-tests/no-only-tests': 'warn',
		'no-param-reassign': 'warn',
		'no-plusplus': 'warn',
		'no-promise-executor-return': 'warn',
		'no-proto': 'warn',
		'no-restricted-exports': 'warn',
		'no-restricted-globals': 'warn',
		'no-restricted-imports': 'warn',
		'no-restricted-properties': 'warn',
		'no-restricted-syntax': 'warn',
		'no-return-assign': 'warn',
		'no-return-await': 'warn',
		'no-script-url': 'warn',
		'no-self-compare': 'warn',
		'no-sequences': 'warn',
		'no-shadow': 'warn',
		'no-template-curly-in-string': 'warn',
		'no-ternary': 'warn',
		'no-throw-literal': 'warn',
		'no-undef-init': 'warn',
		'no-undefined': 'warn',
		'no-underscore-dangle': 'warn',
		'no-unmodified-loop-condition': 'warn',
		'no-unneeded-ternary': 'warn',
		'no-unreachable-loop': 'warn',
		'no-unused-expressions': 'warn',
		'no-unused-private-class-members': 'warn',
		'no-use-before-define': 'warn',
		'no-useless-call': 'warn',
		'no-useless-computed-key': 'warn',
		'no-useless-concat': 'warn',
		'no-useless-constructor': 'warn',
		'no-useless-rename': 'warn',
		'no-useless-return': 'warn',
		'no-var': 'warn',
		'no-void': 'warn',
		'no-warning-comments': 'warn',
		'object-shorthand': 'warn',
		'one-var': 'warn',
		'operator-assignment': 'warn',
		'padding-line-between-statements': 'warn',
		'prefer-arrow-callback': 'warn',
		'prefer-const': 'warn',
		'prefer-destructuring': 'warn',
		'prefer-exponentiation-operator': 'warn',
		'prefer-named-capture-group': 'warn',
		'prefer-numeric-literals': 'warn',
		'prefer-object-has-own': 'warn',
		'prefer-object-spread': 'warn',
		'prefer-promise-reject-errors': 'warn',
		'prefer-regex-literals': 'warn',
		'prefer-rest-params': 'warn',
		'prefer-spread': 'warn',
		'prefer-template': 'warn',
		radix: 'warn',
		'require-atomic-updates': 'warn',
		'require-await': 'warn',
		'require-unicode-regexp': 'warn',
		'sort-imports': 'warn',
		'sort-keys': 'warn',
		'sort-vars': 'warn',
		'spaced-comment': 'warn',
		strict: 'warn',
		'symbol-description': 'warn',
		'vars-on-top': 'warn',
		yoda: 'warn',

		'prettier/prettier': ['error'],
	},

	overrides: [
		{
			files: ['*.test.ts', '*.test.js', '*.spec.ts', '*.spec.js'],
			rules: {
				// PLUGIN: no-only-tests
				'no-only-tests/no-only-tests': 'error',
			},
		},
	],

	settings: {
		'html/html-extensions': ['.html'],
		'import/resolver': {
			node: { extensions: ['.js', '.mjs', '.ts', '.d.ts'] },
		},
	},
}
